### PR TITLE
Added Extra info to front page

### PR DESCRIPTION
**Pull request by RogueElement**
Added the following stats to the front page:

- Ticket Rate of Interest
- Ticket Pool Size
- Ticket Pool Value
- Block Reward Adjustment progress
- Dev Fund balance (In full functionality mode)

### CODE REVIEW

**Comment by raedah** [comment]
tACK

**Comment by raedah** [comment]
dcrdata

**Comment by raedah** [comment]
This closes https://github.com/dcrdata/dcrdata/issues/208

**Comment by chappjc** [comment]
Only comment is that there are three general sections on the left: rewards, ticket pool info, and general (supply, mempool, ticket price, ticket window progress).  It would be good to break up all the info with short horizontal lines/dividers (very subtle, only about as long as 2/3 of the invisible table that holds all the info on the left below ChainState.

But all that styling can wait.  I'm itching go get the address page in and 1.2rc1 tagged and 1.2 branched.  The PR here is good for 1.3 along with the ticket pool auxiliary db: https://github.com/decred/dcrd/pull/981 (needed very soon)

**Pull request merged**
