### PR TITLE
In the case of no vote on the block page

### PR DESCRIPTION
**Pull request by McEdward**
screenshot 14

### CODE REVIEW

**Comment by chappjc** [comment]
Next time please rebase instead of merge.  The others and I can help if you need guidance with this

**Comment by chappjc** [comment]
Still have a conflict to resolve.

**Comment by chappjc** [comment]
@McEdward Github says there are conflicts

**Comment by chappjc** [comment]
You can get the branch updated like this:

```
git checkout master
git pull
git checkout In-The-Case-Of-No-Vote-On-The-Block-Page
git rebase master
# there will be conflicts, with block.tmpl I think
# just open the file in a text editor, find the conflict region, make it the way it should be
git add views/block.tmpl
git rebase --continue
# another conflict in block.tmpl... fix it
git add views/block.tmpl
git rebase --continue
# now it should be done with the rebase.  If git status looks good, then
git push -f
```

**Comment by McEdward** [comment]
Just updated the branch should be all clear

**Pull request merged**
