### PR TITLE
Put version in footer, rearrange items, format.

### PR DESCRIPTION
**Pull request by chappjc**
Built with setting `main.CommitHash`:

image

Built without setting `main.CommitHash` (default):
image

### CODE REVIEW

**Comment by chappjc** [comment]
@dcrdata/explorers How about we try on this look for size?  The primary purpose of this PR was to put the version in the footer, but I ended up tweaking the text and layout too.

**Comment by chappjc** [comment]
Up on https://beta.dcrdata.org/ for testing.

**Comment by RogueElement** [comment]
Seems to work just fine

**Comment by chappjc** [comment]
Just found a template exec error on tx and address pages

**Comment by RogueElement** [comment]
Yeah, just saw that seems the template line is still in the txinfo or addressinfo scope, changing to `{{ template "footer" $.Version }}` should fix it for both

**Comment by chappjc** [comment]
I moved stuff around instead, but you're right that we could have used `$.`

**Pull request merged**
