### PR TITLE
add maturity progress bar to tx.tmpl

### PR DESCRIPTION
**Pull request by gozart1**
As described in #247

Some sample scenarios:

screen shot 2017-10-25 at 2 01 45 am

screen shot 2017-10-25 at 1 51 09 am
screen shot 2017-10-25 at 1 48 19 am

### CODE REVIEW

**Comment by gozart1** [comment]
At 256 confirmations,`.Maturity` is still considered "False", so I've added +1 to the progress logic to make the progress bar represent when it is actually spendable. Does that make sense?

**Comment by gozart1** [comment]
this is still a wip, this should use b.params.TicketMaturity so it works on testnet

**Comment by chappjc** [comment]
I love the concept and the look.  Haven't tested yet though.

**Comment by gozart1** [comment]
alright, updated the progress bar to use the network params and put some better text for when its about ticket progress
screen shot 2017-10-25 at 11 13 36 pm

Thinking this ones ready to go

**Comment by raedah** [comment]
I gave this a test run, looks good.

**Pull request merged**
