### PR TITLE
enable CORS for /api

### PR DESCRIPTION
**Pull request by gozart1**
I've started working on a separate front end and have enabled CORS so that it can make ajax requests. Saw an issue related to this https://github.com/dcrdata/dcrdata/issues/33

New to go so feedback welcome.

### CODE REVIEW

**Comment by chappjc** [comment]
Good find with `rs/cors`.  Looks like this will work, but there are a few changes needed first:

1. Add github.com/rs/cors to glide, the dependency manager: `glide get github.com/rs/cors`, then say "Y" to semantic versioning and "P" to patch releases.  This should update glide.yaml and glide.lock, so you will then need to push those changes too.
2. Middleware, like cors, are currently added in apirouter.go.  I'd suggest putting it in right before `mux.Get("/", app.root)` with something like:

```go
corsMW := cors.Default();
mux.Use(corsMW.Handler)
```

Then finish up with `go fmt $(glide nv)` and it should be good to go.

Thanks for the PR!

**Comment by chappjc** [comment]
Hmm, looks like `github.com/pressly/chi` has moved to `github.com/go-chi/chi`, so it will probably not build after updating glide.  But I can follow up this PR with fixes for that.

**Comment by gozart1** [comment]
Made the suggested changes, squashed and rebased. Thanks for the actionable feedback.

**Comment by chappjc** [comment]
Nice, thanks!

**Pull request merged**
