### PR TITLE
add simple transactions pagination to address.tmpl

### PR DESCRIPTION
**Pull request by gozart1**
This adds some basic pagination UI to address.tmpl 
issue #262

screen shot 2017-11-05 at 1 11 47 pm
screen shot 2017-11-05 at 1 11 41 pm
screen shot 2017-11-05 at 12 48 32 pm
screen shot 2017-11-05 at 12 48 09 pm
screen shot 2017-11-05 at 1 08 13 pm

### CODE REVIEW

**Comment by gozart1** [comment]
Thanks for the feedback.
What do you think about the wording/styling?
Here's some ideas for styling
https://codepen.io/RRoberts/pen/jVOWEQ?q=pagination&limit=all&type=type-pens

I was planning to add page size controls in a separate PR, but could probably manage to add them into this one this evening if thats easier.

**Comment by chappjc** [comment]
I'm not sure which option is best.  It depends on how we show "first" and "last", also how we deal with skipping way ahead if we have say 400 pages.

**Comment by raedah** [comment]
Im noticing that the pagination is different then the blocks page. It may be useful for the user experience to unify and reuse these. Blocks page could probably use page size control as well. For skipping way ahead, could be totally bad ass to have a slider control.

**Comment by gozart1** [comment]
added some page size controls and set default to 20 rows
screen shot 2017-11-05 at 10 45 40 pm
screen shot 2017-11-05 at 10 45 50 pm

**Comment by chappjc** [comment]
The page size looks awesome!

Just two things:

1. The displayed range might need to be tweaked:

> 0 — 20 of 184,107 funding transactions.

I read this as "0 to 20 of ... displayed in the table below."   But with a page size of 2 and 0-based indexing, this is "0 — 19".

And when you click next you get:

> 20 — 40 of 184,108 funding transactions

So tx number 20 would be in both tables if these ranges are accurate.

2. When selecting a new page size from the drop down box, it doesn't load the new page.  You have to click next or previous.

**Comment by gozart1** [comment]
Ok, good catch.
Solved this by adding +1 to the lower bound,
Eg. 1-20 => 21-40 => 41-60

Also, selecting a page size now reloads the current page.

**Comment by chappjc** [comment]
Good stuff!  Going in.

**Pull request merged**
