### PR TITLE
Adding the right age to the first block in Explorer

### PR DESCRIPTION
**Pull request by McEdward**
Resolving issue #214

### CODE REVIEW

**Comment by chappjc** [comment]
Please describe the underlying issue and the solution used to fix it.  Thanks.

**Comment by McEdward** [comment]
I realized that after the age updates it returns to the previous age of 47y 9m @RogueElement how do you suggest i fix this?

**Comment by McEdward** [comment]
I noticed that the 2nd block on the explorer page was showing the age for the first block, which can be noticed if you go into the block pages. So i tried to rearrange it

**Comment by RogueElement** [comment]
@gozart1 should take a look.

**Comment by gozart1** [comment]
Hey guys, sorry about this one. 
Explanation and solution in.
https://github.com/dcrdata/dcrdata/pull/224

**Pull request closed without merging**
