### PR TITLE
Transaction API Endpoint

### PR DESCRIPTION
**Pull request by chappjc**
This is another step toward addressing issue https://github.com/dcrdata/dcrdata/issues/61

The first step was PR https://github.com/dcrdata/dcrdata/pull/69 that added the ability to get transactions for a block (and lookup by block hash).

### CODE REVIEW

**Comment by RogueElement** [comment]
just noticed that the transactions don't have a size field

**Comment by chappjc** [comment]
@RogueElement Tx size added in https://github.com/dcrdata/dcrdata/pull/70/commits/81c67df9560856b5a20a0644abe6fb9cac23dea1.

For reference, here's what we see for http://127.0.0.1:7777/api/tx/8cd50f212ec460be70da0b020010fbeb26180761f0f3cd937663ec601a640039?indent=true:

```json
{
   "size": 200,
   "txid": "8cd50f212ec460be70da0b020010fbeb26180761f0f3cd937663ec601a640039",
   "version": 1,
   "locktime": 0,
   "expiry": 0,
   "vin": [
      {
         "amountin": 17.02786473,
         "blockheight": 0,
         "blockindex": 4294967295,
         "coinbase": "00002f646372642f",
         "sequence": 4294967295
      }
   ],
   "vout": [
      {
         "value": 2.4325521,
         "n": 0,
         "version": 0,
         "scriptPubKey": {
            "asm": "OP_HASH160 f5916158e3e2c4551c1796708db8367207ed13bb OP_EQUAL",
            "reqSigs": 1,
            "type": "scripthash",
            "addresses": [
               ""
            ]
         }
      },
      {
         "value": 0,
         "n": 1,
         "version": 0,
         "scriptPubKey": {
            "asm": "OP_RETURN f1670200000000000000000000000000000000000000000000000000f71d9eea944a3d53",
            "type": "nulldata"
         }
      },
      {
         "value": 14.63554764,
         "n": 2,
         "version": 0,
         "scriptPubKey": {
            "asm": "OP_DUP OP_HASH160 b3c2069c496bc13228c154b03993809f278233d1 OP_EQUALVERIFY OP_CHECKSIG",
            "reqSigs": 1,
            "type": "pubkeyhash",
            "addresses": [
               ""
            ]
         }
      }
   ],
   "confirmations": 4,
   "block": {
      "blockhash": "00000000000000f0d2ccf0e38571d89c47b921210536c65bdbaf32f828ca433b",
      "blockheight": 157681,
      "blockindex": 0,
      "time": 1502124622,
      "blocktime": 1502124622
   }
}```

**Comment by RogueElement** [comment]
Nice

**Comment by chappjc** [comment]
/api/tx/ebf48948e0870d0566f548588a0b160cd3622442c9d4cb01253e2b0d8f072fde/**out**:

```json
[
   {
      "value": 0.0699006,
      "version": 0,
      "pkscript": "76a9146345ef1ed15b758144e00bdeebb6b2b9f934b53788ac"
   },
   {
      "value": 60.96293603,
      "version": 0,
      "pkscript": "76a9146345ef1ed15b758144e00bdeebb6b2b9f934b53788ac"
   },
   {
      "value": 2.01440421,
      "version": 0,
      "pkscript": "76a9146e959bc830f6635e982228a4c015c556170c721188ac"
   }
]
```

/api/tx/ebf48948e0870d0566f548588a0b160cd3622442c9d4cb01253e2b0d8f072fde/**in**:

```json
[
   {
      "prevout": {
         "hash": "c8344b806f894fe9ac648cae9403cb62b4bbcc00926eeed498172b133c3e7416",
         "index": 0,
         "tree": 0
      },
      "sequence": 4294967295,
      "value": 0.06989863,
      "blockheight": 157679,
      "blockindex": 18,
      "sigscript": "483045022100be764cafc76b5e19638830e5eddcb7a81959f6982052dc9011209b44fcfbe8a3022036b52c46b0c39a0f27b56483e61268bbc453581ad536f472f858ec204a8e9f08012103e66252ea1287609313c93673578491f35d5c119111497bfc19062ce32033f333"
   },
   {
      "prevout": {
         "hash": "c8344b806f894fe9ac648cae9403cb62b4bbcc00926eeed498172b133c3e7416",
         "index": 1,
         "tree": 0
      },
      "sequence": 4294967295,
      "value": 60.88789509,
      "blockheight": 157679,
      "blockindex": 18,
      "sigscript": "483045022100e5921db0a3060a67baf57dc5f291a4046bcc863636f0db67f20d30ded321ae140220424b8d65c6e32303d3fc4424d7a137652581c9f0660d4bc3c1f453c16057b7b1012103e66252ea1287609313c93673578491f35d5c119111497bfc19062ce32033f333"
   },
   {
      "prevout": {
         "hash": "c8344b806f894fe9ac648cae9403cb62b4bbcc00926eeed498172b133c3e7416",
         "index": 2,
         "tree": 0
      },
      "sequence": 4294967295,
      "value": 2.09006812,
      "blockheight": 157679,
      "blockindex": 18,
      "sigscript": "4730440220476ec565813ca9c498a80322ced9a8854ad2527116f8b8f08113b7fe50d25511022072bcc76f1153a368a7fc062e5a7a727d4d9f46826dc46384448d8b262c4482dd01210233947c257f372b378f1a7a7a2efe35d622ed2546be7bf299f37db7ad632c0cc2"
   }
]
```

**Comment by chappjc** [comment]
/api/tx/ebf48948e0870d0566f548588a0b160cd3622442c9d4cb01253e2b0d8f072fde/out/**1**:

```json
{
   "value": 60.96293603,
   "version": 0,
   "pkscript": "76a9146345ef1ed15b758144e00bdeebb6b2b9f934b53788ac"
}
```

/api/tx/ebf48948e0870d0566f548588a0b160cd3622442c9d4cb01253e2b0d8f072fde/in/**2**:

```json
{
   "prevout": {
      "hash": "c8344b806f894fe9ac648cae9403cb62b4bbcc00926eeed498172b133c3e7416",
      "index": 2,
      "tree": 0
   },
   "sequence": 4294967295,
   "value": 2.09006812,
   "blockheight": 157679,
   "blockindex": 18,
   "sigscript": "4730440220476ec565813ca9c498a80322ced9a8854ad2527116f8b8f08113b7fe50d25511022072bcc76f1153a368a7fc062e5a7a727d4d9f46826dc46384448d8b262c4482dd01210233947c257f372b378f1a7a7a2efe35d622ed2546be7bf299f37db7ad632c0cc2"
}
```

**Comment by chappjc** [comment]
@gozart1 and @fai04d  Many changes recently.  No DB rebuild or anything, just potential changes from the http JSON API.  This will probably merge today, so heads up.

**Comment by RogueElement** [comment]
Was about to ask for addresses, saw the commit

**Comment by chappjc** [comment]
Addresses in /tx/{txid}/out...

```json
[
   {
      "value": 0.0699006,
      "version": 0,
      "pkscript": "76a9146345ef1ed15b758144e00bdeebb6b2b9f934b53788ac",
      "addresses": [
         "Dsa1pAXSZcY6T951wPbAL41Ev6rznRKrsUA"
      ]
   },
   {
      "value": 60.96293603,
      "version": 0,
      "pkscript": "76a9146345ef1ed15b758144e00bdeebb6b2b9f934b53788ac",
      "addresses": [
         "Dsa1pAXSZcY6T951wPbAL41Ev6rznRKrsUA"
      ]
   },
   {
      "value": 2.01440421,
      "version": 0,
      "pkscript": "76a9146e959bc830f6635e982228a4c015c556170c721188ac",
      "addresses": [
         "Dsb3d3WnJWwK8qK7YgMHFurBkZunXUrPLTP"
      ]
   }
]
```

**Comment by chappjc** [comment]
Please everyone try this out on https://dcrdata.ssgen.io/api, where it's now up.
Note that you can use /api/block/{blockindex}**/tx** or /api/block/hash/{blockhash}**/tx** to get lists of regular and stake transaction hashes in a block, which you may then input to the /api/tx/{txid}... endpoints in this PR

**Comment by RogueElement** [comment]
Looks good

**Pull request merged**
